const questions = [
    "Could you live in another country for the rest of your life?",
    "What's your favorite smoothie or juice recipe?",
    "What do you think about people going to churches or in temples regularly?",
    "Can you tell about a place you've visited?",
    "Would you rather be a famous musician or a renowned chef?",
    "Do you think if you get married that you will change?",
    "Do you think people should be allowed to smoke in public buildings?",
    "Would you rather explore ancient ruins or modern architectural wonders?",
    "What image or metaphor has best described your life? A race, a circus or something else?",
    "What countries in Europe have you visited?",
    "How do you feel about renewable energy sources like solar and wind power?",
    "Do you think that you can you find eternal love through the Internet?",
    "What makes one person more attractive than another?",
    "Have you ever tried riding a skateboard?",
    "What’s your opinion on social media?",
    "Have you ever played an instrument in public?",
    "How can we encourage more sustainable practices in daily life?",
    "Can you tell about your education?",
    "Have you ever ridden a motorcycle?",
    "Do you believe in love at first sight or love after the first night?",
    "Can you tell about your girlfriend?",
    "Should there be limits on the power of multinational corporations?",
    "Do you think it is okay to marry someone with a different religion?",
    "Should the voting age be lowered or raised?",
    "Do you think it is right to continue seeing a person if he has not introduced you to his family yet?",
    "Would you like to go back to the same place?",
    "How many children would you like to have?",
    "What language you like speaking in?",
    "Have you ever walked into a lamppost?",
    "What are your thoughts on the challenges of parenting in today's society?",
    "Do you want to have an international marriage?",
    "Is it OK for women to cry?",
    "What would people think of a man who backs down from a fight?",
    "Is it OK for men to appear sad?",
    "Can you tell me about your first kiss?",
    "Are there different expectations for sons and daughters?",
    "Do you know anyone who is homeless?",
    "Would you rather have the ability to control minds or control the weather?",
    "Can you tell me about your hometown?",
    "Are fathers capable of carrying out the duties of a mother and vice versa?",
    "Should boys and girls be brought up differently?",
    "What is your favorite book or movie?",
    "Do you think it is better to be single or to be married?",
    "What do you need before you can travel to another country?",
    "Is it ethical to eat meat? Why or why not?",
    "What’s your favorite type of transportation?",
    "How long are you going to go for?",
    "Would it be important for you to have a 'white wedding dress'?",
    "Have your parents ever disapproved of any of your relationships?",
    "Do you want a husband or wife who is older, younger or the same age as you?",
    "What are some things that define a culture? For example, music, language, ...",
    "Would you ever consider living permanently in a country other than your home country? Why or why not?",
    "What grammar question have you had lately?",
    "What’s your favorite type of clothing (casual, formal, sporty, etc.)?",
    "Is your home country largely homogeneous?",
    "Have you ever hitchhiked? If so, how many times?",
    "Can you tell me about your favorite music / song / band?",
    "Describe the appearance of the person you would like to date?",
    "What are some ways we can wear words and slogans? i.e. badges, clothes, hats etc.",
    "Why is English used in so many places?",
    "Can you tell me about the worst punishment you had when you were a child?",
    "Who is the greatest actor?",
    "What other languages are spoken in your nation, including minority groups and the languages of immigrants?",
    "What do you think is the color for happiness?",
    "Can you tell me about something you would happily do again?",
    "Who did you go with?",
    "What's your favorite type of sushi roll?",
    "Do you think in vitro fertilization should be available to parents so they can choose the sex of their child?",
    "Are you a morning person or a night owl?",
    "Have you ever explored a country's cuisine in depth during travel?",
    "Do you prefer hot or cold weather?",
    "Do you like to garden?",
    "Would you rather live in a world without music or without art?",
    "Have you ever wondered why Asians can't speak English?",
    "How has technology improved or worsened your quality of life?",
    "Are more teachers female or male in your country?",
    "What does he/she look like?",
    "Can you tell about something boring?",
    "Have you ever made cheesecake?",
    "Have you ever cheated on an exam?",
    "Would you rather have the ability to fly or be invisible?",
    "Would you rather have a job you love with long hours or a job you tolerate with short hours?",
    "How can you become happy again when you are sad?",
    "Is increasing your vocabulary important to you?",
    "Have you ever fallen down the stairs?",
    "Have you ever experimented with unique exercise routines or fitness trends?",
    "Do you think foreign language study should start as early as possible, or is it okay to start later?",
    "Do you prefer to travel by train, bus, plane or ship?",
    "What is the most interesting city to visit in your country?",
    "What’s your favorite childhood cartoon?",
    "Have you ever ridden on an ostrich? A camel? A cow?",
    "What was your worst trip.",
    "Have you ever driven a truck?",
    "How has practicing yoga improved your flexibility and mindfulness?",
    "Can you tell me about your work?",
    "Have you ever been on a blind date?",
    "Do you think self-esteem affects beauty?",
    "What's your opinion on responsible drinking and alcohol consumption?",
    "How much do you usually pay when you eat out?",
    "What do you think 'beauty is skin deep' means?",
    "Do you feel that you have to work hard and be miserable now in order to be happy later?",
    "Do you believe in the concept of karma or fate?",
    "How has technology impacted transportation and commuting?",
    "Can men wear pink clothes?",
    "What's your favorite type of cuisine?",
    "Do you have a large vocabulary?",
    "Should there be limits on freedom of speech?",
    "In your culture is it polite to be straightforward and direct when you talk to someone? To whom is it OK and to whom is it not OK?",
    "What’s your favorite type of technology?",
    "Would you rather have the ability to teleport or time travel?",
    "What do people do at the beach?",
    "Have you ever been trapped in an elevator?",
    "Would you rather live in a world without music or without movies?",
    "What did you do?",
    "Have you ever raised your hand to answer a question, then forgot what you were going to say?",
    "What are some reasons that people become homeless?",
    "What place do you want to visit someday?",
    "What is the best/most important thing your culture has given to the world?",
    "What's your go-to alcoholic beverage for celebrations?",
    "Are you afraid of going abroad alone?",
    "Have you ever built an igloo?",
    "Is going out on dates important for you?",
    "Would you rather have the ability to speak all languages or play all musical instruments?",
    "What's your controversial take on the fairness of the criminal justice system?",
    "Do you think it is okay to marry someone of a different race?",
    "Would you rather be able to fly or breathe underwater?",
    "What’s your favorite type of soup?",
    "How many different adjectives can you think of to describe a beautiful woman or a handsome man",
    "What's the strangest language you have ever head?",
    "What’s your dream job?",
    "How do you think advancements in AI will impact daily life?",
    "Is it common for women and men to take part in sporting activities? Do they take part in the same sports? Are there famous women athletes?",
    "Do you like to watch cooking shows?",
    "Can you tell me about your country?",
    "Do you find more fulfillment from your leisure activities including vacations than from your job?",
    "What's your perspective on the environmental impact of cars?",
    "Do you agree that older people are less happy?",
    "Can you tell me about your computer system?",
    "Have you ever experienced reverse culture shock?",
    "What's your favorite type of workout music?",
    "What do you think of single mothers?",
    "Do you think people with many tattoos can be beautiful?",
    "Have you ever had a crush on someone?",
    "What’s your favorite type of chocolate (dark, milk, white, etc.)?",
    "If you had to choose to live with someone who truly loves you but you don't love him back or to live alone for a rest of your life loving someone that doesn't love you who would you choose?",
    "What's your favorite type of exercise?",
    "What's your favorite non-alcoholic beverage?",
    "Where would you like to go on a date?",
    "When did your parents get married?",
    "What's your go-to drink at a bar?",
    "What are you going to do there?",
    "What's the most miserable you've been?",
    "Do you enjoy studying grammar?",
    "Have you ever been to a live sports event?",
    "What do you think people usually fear when thinking of joining a new religion?",
    "Can you tell me about something you've achieved?",
    "Which is more important for you, your job or your marriage?",
    "Have you ever been to a theme park?",
    "Does your first love still hold a special place in your heart? Do you believe that he or she will always have a special place in your heart?",
    "What makes you unhappy?",
    "Do you like to watch documentaries?",
    "What's your favorite international dish that you love to cook at home?",
    "What country would you like to work in?",
    "Have you ever sung in public?",
    "Do you have pen-friend? If yes, what languages do they speak?",
    "Who is the greatest pop singer?",
    "Should crime punishment focus more on rehabilitation or punishment?",
    "Can you tell me about your favorite restaurant?",
    "What's your favorite type of sandwich filling?",
    "What ethnicity are you?",
    "Do you know much about your own culture?",
    "Is it better to be physically attractive or wealthy?",
    "Have you ever been on a road trip? Where did you go?",
    "Would you rather have the ability to speak all languages or play all musical instruments?",
    "What is or was the happiest time of your life?",
    "Is it better to be physically attractive or intelligent?",
    "Is censorship ever justified? If so, in what circumstances?",
    "Would you rather spend a day at an amusement park or a cultural museum?",
    "Would you introduce your date to your family?",
    "Who would you say is beautiful that others maybe wouldn't?",
    "What's your favorite type of seafood dish?",
    "Why?",
    "If you could go out with anyone, who would it be?",
    "Can you tell about something with four legs?",
    "Do you enjoy going to parties?",
    "Do you believe that money can buy happiness? Why or why not?",
    "How did you get there?",
    "If you had to choose to live with someone who truly loves you but you don't love him back or to live alone for a rest of your life loving someone that doesn't love you what would you choose?",
    "How are your language teachers different from your teachers in your culture? How are they the same?",
    "Have you ever sprained your ankle/wrist? How did it happen?",
    "Do you think studying the grammar of your native language is important?",
    "Have you ever laughed until tears came from your eyes?",
    "Can you tell me about your dreams?",
    "Have you ever gotten lost while traveling? If so, tell about it.",
    "Have you ever fallen or stumbled in front of others.",
    "What kind of man do you want as a husband?",
    "Is there public assistance in your country?",
    "When was the happiest time of your childhood?",
    "What techniques do you use to remember vocabulary?",
    "What is your favorite mode of travel?",
    "Do you think studying the grammar of a foreign language helps you to speak it?",
    "Has the airline ever lost your luggage? What happened?",
    "Can you tell me about the most important lesson you've learnt in life so far?",
    "What’s your favorite color?",
    "When people from other countries think about your culture, what do they usually think of?"
];

function getRandomQuestion() {
    const randomIndex = Math.floor(Math.random() * questions.length);
    document.getElementById("question").innerText = questions[randomIndex];
}
